---
repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v24.7.0
    hooks:
      - id: ansible-lint
        args: [--fix]
        files: \.(yaml|yml)$
        name: Ansible Lint
        description: Run configurations on .ansible-lint file
        verbose: true
        # args: [-p, ./ansible/*]
