---
language: python
dist: bionic
install: pip3 install -r requirements.txt --no-cache-dir

addons:
  apt:
    update: true
    packages:
      - shellcheck

script:
  - ansible-lint -v *.yml
  - shellcheck deploy.sh
