---
language: python
dist: bionic

services: docker

addons:
  apt:
    update: true
    sources:
      - sourceline: "ppa:ansible/ansible"
    packages:
      - ansible-lint
      - ansible

before_install:
  - pip3 install molecule docker

script:
  - cd roles/workstation
  - molecule test
