---
language: python
dist: bionic
install: pip3 install -r requirements.txt --no-cache-dir

addons:
  ansible.builtin.apt:
    update: true
    packages:
      - shellcheck
      - python3-setuptools

script:
  - ansible-lint -v *.yml
  - shellcheck deploy.sh
  - ansible-playbook deploy.yml -e "target=bare"
