---
install_syncthing: yes
install_vscode: yes
install_tlp: yes
configure_alps: no

packages:
  - git
  - vim
  - ansible
  - zsh
  - ShellCheck
  - tmux
  - htop
  - iftop
  - ncdu
  - strace
  - aria2
  - youtube-dl
  - mpv
  - asciinema
  - kubectl

vscode_extensions:
  - ms-python.python
  - technosophos.vscode-helm
  - vscodevim.vim
  - redhat.vscode-yaml
  - mauve.terraform
  - eamodio.gitlens
  - wholroyd.jinja

git:
  name: Łukasz Jendrysik
  email: scadu@disroot.org
  signingkey: 81428558222B6C926149C6814F521D0B0F66261E
  gpgsign: false
