---
install_syncthing: yes
install_vscode: yes
install_chrome: yes
install_kubernetes: yes
install_gcloud: yes
install_tarsnap: yes
install_tlp: no
configure_alps: no

packages:
  - firefox
  - git
  - neovim
  - python3-neovim
  - python3
  - python3-dev
  - python3-venv
  - python3-pip
  - build-essential
  - zsh
  - shellcheck
  - tmux
  - htop
  - iftop
  - ncdu
  - strace
  - aria2
  - youtube-dl
  - mpv
  - asciinema
  - gnome-tweak-tool
  - chrome-gnome-shell

vscode_extensions:
  - ms-python.python
  - vscodevim.vim
  - redhat.vscode-yaml
  - mauve.terraform
  - eamodio.gitlens
  - wholroyd.jinja

git:
  name: Łukasz Jendrysik
  email: scadu@disroot.org
  signingkey: 81428558222B6C926149C6814F521D0B0F66261E
  gpgsign: false
