---
- name: zomg desktop
  hosts: all

  pre_tasks:
    - name: install chrome
      become: yes

      block:
        - name: upgrade system packages
          apt:
            update_cache: yes
            upgrade: dist

        - name: install packages to allow apt to use a repo over https
          package:
            name: "{{ item }}"
            state: present
          with_items:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
          tags:
            - upgrade
            - pre

  roles:
  - role: workstation
    tags: ['workstation']


    vars:
    # available params: "desktop", "wsl"
    # see available files in vars/
    install_type: "desktop"
