#!/bin/bash -e
# Source: https://github.com/cdown/ansible-desktop/blob/d6dccb7983190d72bcc2f9b6ef11c5eac3487bd2/run

config_file=$HOME/.ansibleconfig

if ! [[ -e $config_file ]]; then
    read -r -p 'Config: ' AS_CONFIG
    echo "$AS_CONFIG" > "$config_file"
fi

AS_CONFIG=$(cat "$config_file")
export AS_CONFIG

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check if Ansible is installed
if ! command_exists ansible; then
    echo "Ansible is not installed. Installing now..."
    sudo apt-get update
    sudo apt-get install -y ansible

fi

# Check if ansible-playbook is available
if ! command_exists ansible-playbook; then
    echo "Error: ansible-playbook command not found. Please ensure Ansible is correctly installed."
    exit 1
fi

ansible-playbook -c local -i localhost, -K setup.yaml