---
- name: zomg desktop
  hosts: all
  roles:
  - role: workstation
    tags: ['workstation']

    vars:

    # available params: "desktop", "wsl"
    # see available files in vars/
    install_type: "desktop"
