---
- name: zomg desktop
  hosts: all

  vars_files:
        "vars/{{ target }}.yml"

  roles:
    - role: workstation
      tags: ["workstation"]

  pre_tasks:
    - name: prepare system
      become: true

      block:
        - name: upgrade system packages
          apt:
            update_cache: yes
            upgrade: yes

  post_tasks:
    - name: check if reboot is required

      block:
        - name: check if reboot is required
          stat:
            path: "/var/run/reboot-required"
          register: reboot_required

        - debug:
            msg: "Reboot required!"
          when: reboot_required.stat.isreg is defined
      tags:
        - post_tasks

  # Do not yell about missing aptitude
  # https://github.com/ansible/ansible/pull/61782
  module_defaults:
    apt:
      force_apt_get: yes
