---
- hosts: localhost
  connection: local

  vars:
    desktop: false
  
- include_tasks: tasks/vscode.yaml
  tags:
    - vscode
    - dev 
- include_tasks: tasks/shell.yaml
  tags:
    - shell
    - dev
- include_tasks: tasks/gh.yaml
  tags:
    - gh
    - github
    - dev
- include_tasks: tasks/chrome.yaml
  tags:
    - chrome
    - desktop
- include_tasks: tasks/1password.yaml
  tags:
    - 1password
    - desktop
- include_tasks: tasks/magic.yaml
  tags:
    - magic
    - desktop
- include_tasks: tasks/dnf.yaml
  tags:
    - dnf
- include_tasks: packages.yaml
  tags:
    - packages
- include_tasks: tasks/gnome.yaml
  tags:
    - gnome
    