---
- hosts: localhost
  connection: local

  vars:
    desktop: false

  vars_files:
      - "vars/{{ lookup('env', 'AS_CONFIG') }}.yaml"

  tasks:  
  - include_vars: vars/main.yaml
  - include_tasks: tasks/vscode.yaml
    tags:
      - vscode
    when: desktop
  - include_tasks: tasks/shell.yaml
    tags:
      - shell
      - dev
  - include_tasks: tasks/gh.yaml
    tags:
      - gh
      - github
      - dev
  - include_tasks: tasks/chrome.yaml
    tags:
      - chrome
      - desktop
    when: desktop
  - include_tasks: tasks/1password.yaml
    tags:
      - 1password
      - desktop
    when: desktop
  - include_tasks: tasks/magic.yaml
    tags:
      - magic
      - desktop
  - include_tasks: tasks/dnf.yaml
    tags:
      - dnf
  - include_tasks: tasks/packages.yaml
    tags:
      - packages
  - include_tasks: tasks/gnome.yaml
    tags:
      - gnome
    when: desktop
  - include_tasks: tasks/ssh.yaml
    tags:
      - ssh
    when: desktop
      