---
- name: install 1password
  become: true

  block:
    - name: add 1password repo
      ansible.builtin.yum_repository:
        name: 1password
        description: "{{ rpm_repos.onepassword.name }}"
        baseurl: "{{ rpm_repos.onepassword.baseurl }}"
        gpgcheck: true
        gpgkey: "{{ rpm_repos.onepassword.gpgkey }}"
        repo_gpgcheck: true

    - name: install 1password
      ansible.builtin.dnf:
        name: 1password
        state: present