---
- name: install vscode
  become: true

  block:
    # - name: add vscode repo key
    #   ansible.builtin.rpm_key:
    #     state: present
    #     key: "{{ vscode_repo_key }}"

    - name: add vscode repo
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: true
        gpgkey: "{{ vscode_repo_key }}"

    - name: install vscode
      ansible.builtin.dnf:
        name: code
        state: latest