---
- name: Install 1password
  become: true

  block:
    - name: Add 1password repo
      ansible.builtin.yum_repository:
        name: 1password
        description: "{{ rpm.onepassword.name }}"
        baseurl: "{{ rpm.onepassword.baseurl }}"
        gpgcheck: true
        gpgkey: "{{ rpm.onepassword.gpgkey }}"
        repo_gpgcheck: true

    - name: Install 1password
      ansible.builtin.dnf:
        name:
          - 1password
          - 1password-cli
        state: present
