---
- name: install chrome
  become: true

  block:
    - name: fedora install chrome
      ansible.builtin.dnf:
        state: present
        enablerepo: google-chrome
        name:
          - google-chrome-stable
