---
- name: Configure git and GitHub CLI
  block:
    - name: Add GitHub CLI repository signing key
      ansible.builtin.apt_key:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        state: present
      become: true

    - name: Add GitHub CLI repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://cli.github.com/packages stable main
        state: present
        filename: github-cli
      become: true

    - name: Install git tooling
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - git-delta
        - gh
        - pre-commit
      become: true

    - name: Set up gitconfig
      ansible.builtin.template:
        src: templates/gitconfig.j2
        dest: "{{ ansible_user_dir }}/.gitconfig"
        force: false # copy only if file does not exist on the target
        mode: "0644"