---
- name: Install zsh
  become: true
  ansible.builtin.dnf:
    state: present
    name: zsh

- name: Install antidote plugin manager
  ansible.builtin.git:
    repo: https://github.com/mattmc3/antidote
    dest: "{{ ansible_user_dir }}/.antidote"
    version: main
    depth: 1

- name: Copy .zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: 644

- name: Set zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    update_password: on_create
    shell: /bin/zsh

- name: Enable starship copr
  become: true
  community.general.copr:
    state: enabled
    name: atim/starship

- name: Install starship, zoxide and othe utils
  become: true
  ansible.builtin.dnf:
    name:
      - starship
      - zoxide
      - fzf # In case if already not installed as dependency for zoxide
    state: present
