---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    state: present
    name: zsh
    update_cache: yes

- name: Install antidote plugin manager
  ansible.builtin.git:
    repo: https://github.com/mattmc3/antidote
    dest: "{{ ansible_user_dir }}/.antidote"
    version: main
    depth: 1

- name: Copy .zsh_plugins.txt
  ansible.builtin.copy:
    src: .zsh_plugins.txt
    dest: "{{ ansible_user_dir }}/.zsh_plugins.txt"
    mode: "0644"

- name: Generate zshrc
  ansible.builtin.template:
    src: templates/{{ item }}.j2
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
  with_items:
    - zshrc
    - zshenv

- name: Set zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    update_password: on_create
    shell: /bin/zsh

- name: Install Starship
  block:
    - name: Ensure ~/bin directory exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/bin"
        state: directory
        mode: '0755'

    - name: Get latest Starship release
      community.general.github_release:
        user: starship
        repo: starship
        action: latest_release
      register: starship_release

    - name: Download Starship binary
      ansible.builtin.get_url:
        url: "https://github.com/starship/starship/releases/download/{{ starship_release.tag }}/starship-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/tmp/starship.tar.gz"
        mode: '0644'

    - name: Extract Starship binary
      ansible.builtin.unarchive:
        src: "/tmp/starship.tar.gz"
        dest: "{{ ansible_user_dir }}/bin"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set Starship binary permissions
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/bin/starship"
        mode: '0755'

- name: Install zoxide and other utils
  become: true
  ansible.builtin.apt:
    name:
      - zoxide
      - fzf
      - ripgrep
      - jq
    state: present
    update_cache: yes