---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    state: present
    name: zsh
    update_cache: yes

- name: Install antidote plugin manager
  ansible.builtin.git:
    repo: https://github.com/mattmc3/antidote
    dest: "{{ ansible_user_dir }}/.antidote"
    version: main
    depth: 1

- name: Copy .zsh_plugins.txt
  ansible.builtin.copy:
    src: .zsh_plugins.txt
    dest: "{{ ansible_user_dir }}/.zsh_plugins.txt"
    mode: "0644"

- name: Generate zshrc
  ansible.builtin.template:
    src: templates/{{ item }}.j2
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
  with_items:
    - zshrc
    - zshenv

- name: Set zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    update_password: on_create
    shell: /bin/zsh

- name: Install Starship
  block:
    - name: Ensure ~/bin directory exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/bin"
        state: directory
        mode: '0755'

    - name: Get latest Starship release info
      ansible.builtin.uri:
        url: https://api.github.com/repos/starship/starship/releases/latest
        return_content: yes
      register: starship_release_info

    - name: Set Starship version
      ansible.builtin.set_fact:
        starship_version: "{{ starship_release_info.json.tag_name }}"

    - name: Download Starship binary
      ansible.builtin.get_url:
        url: "https://github.com/starship/starship/releases/download/{{ starship_version }}/starship-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/tmp/starship.tar.gz"
        mode: '0644'

    - name: Debug - List content of /tmp
      ansible.builtin.command: ls -l /tmp/starship.tar.gz
      register: ls_tmp_result

    - name: Debug - Show ls result
      ansible.builtin.debug:
        var: ls_tmp_result.stdout_lines

    - name: Create temporary directory for extraction
      ansible.builtin.tempfile:
        state: directory
        suffix: starship
      register: tempdir

    - name: Extract Starship binary to temporary directory
      ansible.builtin.unarchive:
        src: "/tmp/starship.tar.gz"
        dest: "{{ tempdir.path }}"
        remote_src: yes
      register: extract_result

    - name: Debug - Show extract result
      ansible.builtin.debug:
        var: extract_result

    - name: Debug - List content of temp directory
      ansible.builtin.command: ls -l {{ tempdir.path }}
      register: ls_temp_result

    - name: Debug - Show temp directory content
      ansible.builtin.debug:
        var: ls_temp_result.stdout_lines

    - name: Move Starship binary to ~/bin
      ansible.builtin.copy:
        src: "{{ tempdir.path }}/starship"
        dest: "{{ ansible_user_dir }}/bin/starship"
        mode: '0755'
        remote_src: yes

    - name: Debug - List content of ~/bin
      ansible.builtin.command: ls -l {{ ansible_user_dir }}/bin
      register: ls_bin_result

    - name: Debug - Show ls result
      ansible.builtin.debug:
        var: ls_bin_result.stdout_lines

    - name: Remove Starship archive and temp directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/starship.tar.gz"
        - "{{ tempdir.path }}"

  rescue:
    - name: Debug - Show error
      ansible.builtin.debug:
        msg: "An error occurred during Starship installation. Please check the output above for details."

    - name: Fail the play if Starship installation failed
      ansible.builtin.fail:
        msg: "Starship installation failed. Please review the debug output and try again."

- name: Install zoxide and other utils
  become: true
  ansible.builtin.apt:
    name:
      - zoxide
      - fzf
    state: present
    update_cache: yes