---
- name: Install vscode
  become: true

  block:
    - name: Add vscode repo
      ansible.builtin.yum_repository:
        name: vscode
        description: "{{ rpm.vscode.name }}"
        baseurl: "{{ rpm.vscode.baseurl }}"
        gpgcheck: true
        gpgkey: "{{ rpm.vscode.gpgkey }}"

    - name: Install vscode
      ansible.builtin.dnf:
        name: code
        state: present
