---

# https://bugs.freedesktop.org/show_bug.cgi?id=106425
- name: configure Alps touchpad
  become: yes
  tags:
    - touchpad

  block:
  - name: apply hwdb touchpad configuration
    template:
      src: templates/99-touchpad-pressure.hwdb.j2
      dest: /etc/udev/hwdb.d/99-touchpad-pressure.hwdb
      owner: root
      group: root
      mode: 0644