---
- name: install AWS tools
  
  block:
  - name: make sure that required directories exists
    file: 
      name: "{{ item }}"
      state: directory
      owner: "{{ ansible_user_id }}"
    with_items:
      - "{{ user_local_dir }}/bin"
      - "{{ user_local_dir }}/aws-vault"

  - name: install AWS tools via pip
    pip:
      name: "{{ aws_tools }}"
      extra_args: "--user"
      executable: pip3

  - name: download aws-vault binary
    get_url:
      url: "{{ aws_vault_url }}"
      dest: "{{ user_local_dir }}/aws-vault/"
      checksum: "{{ aws_vault_checksum }}"
      mode: '0700'

  - name: link aws-vault binary
    file:
      state: link
      path: "{{ user_local_dir }}/bin/aws-vault"
      src: "{{ user_local_dir }}/aws-vault/aws-vault-linux-amd64"