---
- name: install AWS tools

  block:
    - name: make sure that required directories exists
      file:
        name: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
      with_items:
        - "{{ user_local_dir }}/bin"

    - name: install AWS tools via pip
      pip:
        name: "{{ aws_tools }}"
        extra_args: "--user"
        executable: pip3
