---
- name: configure dnf
  become: yes
  tags:
    - dnf_config

  block:
  - name: configure dnf.conf
    template:
      src: templates/dnf.conf.j2
      dest: /etc/dnf/dnf.conf
      owner: root
      group: root
      mode: 0644