---
- name: install docker
  become: true

  block:
    - name: add docker upstream repo key
      apt_key:
        url: "{{ docker_repo_key }}"
        state: present

    - name: add docker upstream repository
      apt_repository:
        repo: "{{ docker_repo }}"
        filename: docker
        state: present

    - name: install docker from upstream repository
      apt:
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: add my user to docker group
      become: true

      user:
        name: "{{ ansible_user_id }}"
        update_password: on_create
        groups: docker
        append: yes
