---
- name: install docker
  become: yes
  
  block:
  - name: install docker
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - docker.io

  - name: import docker-compose install task
    import_tasks: docker_compose.yml