---
- name: install docker-compose
  block:
    - name: install python3-pip
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: install docker-compose
      pip:
        name: docker-compose
        extra_args: "--user"
        executable: pip3
