---
- name: install docker
  become: yes

  block:
    - name: install docker
      apt:
        state: present
        name:
          - docker.io

    - name: add my user to docker group
      become: yes

      user:
        name: "{{ ansible_user_id }}"
        update_password: on_create
        groups: docker
        append: yes

    - name: install docker-compose
      pip:
        name: docker-compose
        extra_args: "--user"
        executable: pip3
