---
- name: install docker
  become: yes
  
  block:
  - name: add docker repo key
    apt_key:
        url: "{{ docker_repo_key }}"
        state: present

  - name: add docker repository
    apt_repository:
      repo: "{{ docker_repo }}"
      filename: docker
      state: present

  - name: install docker
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io