---
- name: install docker
  become: yes

  block:
    - name: install docker
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io

    - name: add my user to docker group
      become: yes

      user:
        name: "{{ ansible_user_id }}"
        update_password: on_create
        groups: docker
        append: yes

    - name: import docker-compose install task
      import_tasks: docker_compose.yml
