---
- name: install dotfiles

  block:
    - name: install zsh
      become: yes
      apt:
        name: zsh
        state: present

    - name: clone oh-my-zsh repo
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: "{{ ansible_user_dir }}/.oh-my-zsh"

    - name: generate config files
      template:
        src: "templates/{{ item }}.j2"
        dest: "{{ ansible_user_dir }}/.{{ item }}"
        owner: "{{ ansible_user_id }}"
      with_items:
        - gitconfig
        - gitignore
        - zshrc
