---
- name: install dotfiles

  block:
    - name: install zsh
      become: true
      apt:
        name: zsh
        state: present

    - name: clone oh-my-zsh repo
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: "{{ ansible_user_dir }}/.oh-my-zsh"
        version: master

    - name: clone powerlevel10k
      git:
        repo: https://github.com/romkatv/powerlevel10k
        dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/powerlevel10k"
        version: master

    - name: copy fonts for p10k
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/.local/share/fonts/"
        owner: "{{ ansible_user_id }}"
      with_fileglob:
        - "files/fonts/*.ttf"
      notify: refresh font cache

    - name: generate config files
      template:
        src: "templates/{{ item }}.j2"
        dest: "{{ ansible_user_dir }}/.{{ item }}"
        owner: "{{ ansible_user_id }}"
      with_items:
        - gitconfig
        - gitignore
        - zshrc

    - name: copy p10k config
      copy:
        src: "files/{{ item }}"
        dest: "{{ ansible_user_dir }}/.{{ item }}"
        owner: "{{ ansible_user_id }}"
        mode: 0600
      with_items:
        - p10k.zsh
