---
- name: install dotfiles

  block:
    - name: install zsh
      become: yes
      apt:
        name: zsh
        state: present

    - name: generate gitconfig
      template:
        src: "templates/{{ item }}.j2"
        dest: "{{ ansible_user_dir }}/.{{ item }}"
        owner: "{{ ansible_user_id }}"
      with_items:
        - gitconfig
        - gitignore

    - name: copy zshrc
      copy:
        src: "files/{{ item }}"
        dest: "{{ ansible_user_dir }}/.{{ item }}"
        owner: "{{ ansible_user_id }}"
      with_items:
        - zshrc
        - zshrc.local
