---
- name: install python3-psutil
  become: true
  ansible.builtin.apt:
    name: python3-psutil
    state: present

- name: install GNOME packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - gnome-tweaks  

- name: configure dock
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "hot-keys", value: "false" }
    - { key: "dock-position", value: "'RIGHT'" }
    - { key: "dock-fixed", value: "false" }
    - { key: "dash-max-icon-size", value: "32" }

- name: set focus wm click focus, disable audible bell
  dconf:
    key: "/org/gnome/desktop/wm/preferences/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "focus-mode", value: "'click'" }
    - { key: "audible-bell", value: "false" }

- name: set interface misc settings
  dconf:
    key: "/org/gnome/desktop/interface/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "enable-animations", value: "false" }
    - { key: "show-battery-percentage", value: "true" }

- name: enable clearing old trash and temp files
  dconf:
    key: "/org/gnome/desktop/privacy/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "remove-old-temp-files", value: "true" }
    - { key: "old-files-age", value: "uint32 7" }
    - { key: "remove-old-trash-files", value: "true" }

- name: hide home and trash icons from desktop
  dconf:
    key: "/org/gnome/shell/extensions/desktop-icons/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "show-home", value: "false" }
    - { key: "show-trash", value: "false" }

- name: set notifications preferences
  dconf:
    key: "/org/gnome/desktop/notifications/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "show-in-lock-screen", value: "false" }

- name: set shell settings
  dconf:
    key: "/org/gnome/shell/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "enable-hot-corners", value: "true" }

- name: set workspaces
  dconf:
    key: "/org/gnome/mutter/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "dynamic-workspaces", value: "false" }
    - { key: "workspaces-only-on-primary", value: "true" }
