---
- name: install Go

  block:
    - name: download Go binary
      get_url:
        url: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/tmp/go-{{ go_version }}.linux-amd64.tar.gz"
        checksum: "{{ go_checksum }}"

    - name: extract Go archive
      become: yes
      unarchive:
        src: "/tmp/go-{{ go_version }}.linux-amd64.tar.gz"
        dest: "/usr/local/"

  always:
    - name: remove Go tarball
      file:
        path: "/tmp/go-{{ go_version }}.linux-amd64.tar.gz"
        state: absent
