---
- name: install helm
  tags:
    - helm

  block:
    - name: make sure that bin and helm dirs exists
      file: 
        name: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
      with_items:
        - "{{ user_local_dir }}/bin"
        - "{{ user_local_dir }}/helm"

    - name: download helm
      get_url:
        url: "{{ helm_url }}"
        dest: /tmp/helm.tar.gz
        checksum: "{{ helm_checksum }}"

    - name: extract helm binary
      unarchive:
        src: /tmp/helm.tar.gz
        dest: "{{ user_local_dir }}/helm"

    - name: link helm binary
      file:
        state: link
        path: "{{ user_local_dir }}/bin/helm"
        src: "{{ user_local_dir }}/helm/linux-amd64/helm"
