---
- name: configure journald
  become: yes
  
  block:
  - name: apply journald configuration
    template:
      src: templates/journald.conf.j2
      dest: /etc/systemd/journald.conf
      owner: root
      group: root
      mode: 0644
    notify: restart journald
