---
# https://www.mail-archive.com/kernel-packages@lists.launchpad.net/msg495367.html
# https://discourse.ubuntu.com/t/why-ubuntu-22-04-is-so-fast-and-how-to-make-it-faster/30369
- name: make mutter go brr
  become: true
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "^MUTTER_DEBUG_FORCE_KMS_MODE"
    line: MUTTER_DEBUG_FORCE_KMS_MODE=0

# https://www.phoronix.com/news/Linux-6.1-rc7-Easier-AMD-Pstate
- name: enable amd-pstate
  become: true
  ansible.builtin.command:
    cmd: 'grubby --update-kernel=ALL --args="amd_pstate=passive"'
  when: |
    ansible_processor | intersect(["AuthenticAMD"]) 
    and ansible_kernel is version('6.1', '>=')
