---
- include_vars: vars/{{ install_type }}_config.yml
  when: install_type is defined and install_type == "wsl" or "desktop"
  tags:
    - always

- import_tasks: upgrade.yml
  tags:
    - upgrade

- import_tasks: user.yml

- import_tasks: packages.yml
  when: packages is defined
  tags:
    - packages

- import_tasks: remove_dock.yml
  when: remove_dock | default(False)

- import_tasks: scripts.yml
  when: install_scripts | default(False)
  tags:
    - scripts

- import_tasks: terraform.yml
  when: install_terraform | default(False)
  tags:
    - terraform

- import_tasks: syncthing.yml
  when: install_syncthing | default(False)
  tags:
    - syncthing

- import_tasks: journald.yml
  when: configure_journald | default(False)
  tags:
    - journald
    - sytemd

- import_tasks: vscode.yml
  when: install_vscode | default(False)
  tags:
    - vscode

- import_tasks: chrome.yml
  when: install_chrome | default(False)
  tags:
    - chrome

- import_tasks: tarsnap.yml
  when: install_tarsnap | default(False)
  tags:
    - tarsnap

- import_tasks: kubernetes.yml
  when: install_kubernetes | default(False)
  tags:
    - kubernetes

- import_tasks: helm.yml
  when: install_kubernetes | default(False)
  tags:
    - kubernetes
    - helm

- import_tasks: gcloud.yml
  when: install_gcloud | default(False)
  tags:
    - gcloud

- import_tasks: alps.yml
  when: ansible_product_name == "Latitude E7240" and configure_alps | default(False)
  tags:
    - alps
    - touchpad

- import_tasks: tlp.yml
  when: install_tlp | default(False)
  tags:
    - tlp

- import_tasks: signal.yml
  when: install_signal | default(False)
  tags:
    - signal

- import_tasks: dotfiles.yml
  when: install_dotfiles | default(False)
  tags:
    - dotfiles

- import_tasks: python.yml
  when: install_python | default(False)
  tags:
    - python