---
- name: install common packages
  become: yes
  tags:
    - packages

  block:
  - name: install common packages
    package:
      name: "{{ packages }}"
      state: present

- name: install flatpak
  become: yes
  tags:
    - packages
    - flatpak

  block:
  - name: install flatpak
    package:
      name: flatpak
      state: present

  - name: add flathub remote
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: "{{ flathub_repo }}"

  - name: install spotify flatpak
    flatpak:
      name: "{{ flatpak_spotify }}"
      state: present

  - name: install signal flatpak
    flatpak:
      name: "{{ flatpak_signal }}"
      state: present

  - name: install telegram flatpak
    flatpak:
      name: "{{ flatpak_telegram }}"
      state: present

- name: install devl basis
  become: yes
  tags:
    - packages
    - devel

  block:
  - name: install devel basis
    package:
      name: devel_basis
      type: pattern
      state: present

  - name: install python3-devel
    package:
      name: python3-devel
      state: present