---
- name: install common packages
  become: yes
  tags:
    - packages

  block:
  - name: install the rpmfusion repo packages
    become: yes
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm

  - name: install common packages
    package:
      name: "{{ packages }}"
      state: present

  - name: install Flatpak
    become: yes

    package:
      name: flatpak
      state: present

  - name: add Flathub repo
    flatpak_remote:
      name: Flathub
      state: present
      flatpakrepo_url: "{{ flathub_repo }}"

  - name: install Spotify flatpak
    flatpak:
      name: "{{ flatpak_spotify_ref }}"
      state: present

  - name: install Signal flatpak
    flatpak:
      name: "{{ flatpak_signal_ref }}"
      state: present