---
- name: install packages to allow apt to use a repo over https
  become: yes
  
  block:
  - name: install packages to allow apt to use a repo over https
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common