---
- name: "configure PRIME (hybrid graphics)"

  block:
    - name: check if nvidia-prime installed
      command: which prime-select
      changed_when: false
      failed_when: prime_installed.rc not in [0,1]
      register: prime_installed

    - name: select desired graphic
      become: yes
      command: prime-select "{{ graphic_card }}"
      when: prime_installed.rc == 0
