---
- name: install python system packages
  tags:
    - python

  block:
  - name: install python3 system packages
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - python3-dev
      - python3-pip
      - python3-venv

  - name: install pip packages
    pip:
      executable: pip3
      extra_args: --upgrade --user
      name:
        - awscli
