---
- name: install python system packages

  block:
  - name: install python3 system packages
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - python3-dev
      - python3-pip
      - python3-pytest
      - python3-venv