---

- name: add packman repository
  become: yes
  tags:
    - repo_packman
    - repos
    
  block:
  - name: add packman repository
    zypper_repository:
      name: packman
      repo: 'http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_{{ ansible_distribution_version }}/'
      state: present
      auto_import_keys: yes
      runrefresh: yes
  
  - name: change vendor for packages available in packman repo
    shell:  zypper dup -y --from packman --allow-vendor-change
    warn: False

- name: add security repository
  become: yes
  zypper_repository:
    name: security
    repo: 'https://download.opensuse.org/repositories/security/openSUSE_Leap_{{ ansible_distribution_version }}/'
    state: present
    auto_import_keys: yes
    runrefresh: yes
  tags:
    - repo_security
    - repos