---

- name: add packman repository
  become: yes
  tags:
    - repo_packman
    - repos
    
  block:
  - name: add packman repository
    zypper_repository:
      name: packman
      repo: "{{ packman_repo }}"
      state: present
      auto_import_keys: yes
      runrefresh: yes
  
  - name: change vendor for packages available in packman repo
    shell:  zypper dup -y --from packman --allow-vendor-change
    warn: False

- name: add security repository
  become: yes
  zypper_repository:
    name: security
    repo: "{{ security_repo }}"
    state: present
    auto_import_keys: yes
    runrefresh: yes
  tags:
    - repo_security
    - repos