---
- name: check if script directory is not empty
  find:
    paths: "{{ playbook_dir }}/scripts/"
    file_type: file
    patterns: .*\.(sh|py)
    use_regex: yes
  changed_when: false
  register: scripts

- name: install scripts
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/bin/"
    mode: 0755
  with_fileglob:
    - "{{ playbook_dir }}/scripts/*"
  when: scripts.matched|int != 0
