---
- name: install zsh
  become: true
  ansible.builtin.dnf:
    state: present
    name: zsh

- name: install antidote plugin manager
  ansible.builtin.git:
    repo: https://github.com/mattmc3/antidote
    dest: "{{ ansible_user_dir }}/.antidote"
    depth: 1

- name: copy .zsh_plugins.txt
  ansible.builtin.copy:
    src: .zsh_plugins.txt
    dest: "{{ ansible_user_dir }}/.zsh_plugins.txt"

- name: generate zshrc
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    owner: "{{ ansible_user_id }}"
  with_items:
    - zshrc

- name: set zsh as default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    update_password: on_create
    shell: /bin/zsh

- name: enable starship copr
  become: true
  community.general.copr:
    state: enabled
    name: atim/starship

- name: install starship
  become: true
  ansible.builtin.dnf:
    name: starship
    state: present
