- name: apply sysctl settings
  become: true
  sysctl:
    sysctl_file: /etc/sysctl.d/10-custom.conf
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: true
  with_items:
    - { key: "fs.inotify.max_user_watches", value: "524288" }
    - { key: "vm.swappiness", value: "10" }
