---
- name: install tfenv

  block:
    - name: make sure that bin, tfenv dirs exists
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
      with_items:
        - "{{ user_local_dir }}/bin"
        - "{{ user_local_dir }}/tfenv"

    - name: download tfenv
      ansible.builtin.get_url:
        url: "https://github.com/tfutils/tfenv/v{{ tfenv_version }}.tar.gz"
        dest: /tmp/tfenv.zip

    - name: extract tfenv scripts
      ansible.builtin.unarchive:
        src: /tmp/tfenv.zip
        dest: "{{ user_local_dir }}/tfenv"

    - name: link tfenv scripts/binaries
      ansible.builtin.file:
        state: link
        mode: "0700"
        path: "{{ item.path }}"
        src: "{{ item.src }}"
      with_items:
        - {
            src: "{{ user_local_dir }}/tfenv/tfenv-{{ tfenv_version }}/bin/tfenv",
            path: "{{ user_local_dir }}/bin/tfenv",
          }
        - {
            src: "{{ user_local_dir }}/tfenv/tfenv-{{ tfenv_version }}/bin/terraform",
            path: "{{ user_local_dir }}/bin/terraform",
          }

  always:
    - name: remove tfenv tarball
      ansible.builtin.file:
        path: /tmp/tfenv.zip
        state: absent
