---
- name: install tfenv

  block:
    - name: make sure that bin, terragrunt and tfenv dirs exists
      file: 
        name: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
      with_items:
        - "{{ user_local_dir }}/bin"
        - "{{ user_local_dir }}/tfenv"
        - "{{ user_local_dir }}/terragrunt"

    - name: download tfenv
      get_url:
        url: "{{ tfenv_url }}"
        dest: /tmp/tfenv.zip
        checksum: "{{ tfenv_checksum }}"

    - name: extract tfenv scripts
      unarchive:
        src: /tmp/tfenv.zip
        dest: "{{ user_local_dir }}/tfenv"

    - name: download terragrunt binary
      get_url:
        url: "{{ terragrunt_url }}"
        dest: "{{ user_local_dir }}/terragrunt/terragrunt"
        checksum: "{{ terragrunt_checksum }}"

    - name: link tfenv and terragrunt scripts/binaries
      file:
        state: link
        mode: '0700'
        path: "{{ item.path }}"
        src: "{{ item.src }}"
      with_items:
        - { src: "{{ user_local_dir }}/tfenv/tfenv-{{ tfenv_version }}/bin/tfenv", path: "{{ user_local_dir }}/bin/tfenv" }
        - { src: "{{ user_local_dir }}/tfenv/tfenv-{{ tfenv_version }}/bin/terraform", path: "{{ user_local_dir }}/bin/terraform" }
        - { src: "{{ user_local_dir }}/terragrunt/terragrunt", path: "{{ user_local_dir }}/bin/terragrunt" }
