---
- name: install tfenv

  block:
    - name: make sure that bin, terragrunt and tfenv dirs exists
      file:
        name: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
      with_items:
        - "{{ ansible_user_dir }}/bin"
        - "{{ ansible_user_dir }}/tfenv"
        - "{{ ansible_user_dir }}/terragrunt"

    - name: download tfenv
      get_url:
        url: "{{ tfenv_url }}"
        dest: /tmp/tfenv.zip
        checksum: "{{ tfenv_checksum }}"

    - name: extract tfenv scripts
      unarchive:
        src: /tmp/tfenv.zip
        dest: "{{ ansible_user_dir }}/tfenv"

    - name: download terragrunt binary
      get_url:
        url: "{{ terragrunt_url }}"
        dest: "{{ ansible_user_dir }}/terragrunt/terragrunt"
        checksum: "{{ terragrunt_checksum }}"

    - name: link tfenv and terragrunt scripts/binaries
      file:
        state: link
        mode: "0700"
        path: "{{ item.path }}"
        src: "{{ item.src }}"
      with_items:
        - {
            src: "{{ ansible_user_dir }}/tfenv/tfenv-{{ tfenv_version }}/bin/tfenv",
            path: "{{ ansible_user_dir }}/bin/tfenv",
          }
        - {
            src: "{{ ansible_user_dir }}/tfenv/tfenv-{{ tfenv_version }}/bin/terraform",
            path: "{{ ansible_user_dir }}/bin/terraform",
          }
        - {
            src: "{{ ansible_user_dir }}/terragrunt/terragrunt",
            path: "{{ ansible_user_dir }}/bin/terragrunt",
          }

  always:
    - name: remove tfenv tarball
      file:
        path: /tmp/tfenv.zip
        state: absent
