---
- name: install terraform
  tags:
    - terraform

  block:
    - name: make sure that bin dir exists
      file: 
        path: "{{ user_local_dir }}/bin"
        state: directory
        owner: "{{ ansible_user_id }}"

    - name: download terraform
      get_url:
        url: "{{ terraform_url }}"
        dest: /tmp/terraform.zip
        checksum: "{{ terraform_checksum }}"

    - name: extract terraform binary
      unarchive:
        src: /tmp/terraform.zip
        dest: "{{ user_local_dir }}/bin"
