---
- name: install and configure TLP
  become: yes

  block:
  - name: install TLP
    package:
      name: tlp
      state: present
    
  - name: apply TLP configuration
    template:
      src: templates/tlp.j2
      dest: /etc/default/tlp
      owner: root
      group: root
      mode: 0644
    notify: 
      - start tlp
      - mask systemd-rfkill