---
- name: install vscode snap
  become: yes
  snap:
    name: code
    state: present
    classic: yes

- name: install vscode extensions
  command: "code --install-extension '{{ item }}'"
  loop: "{{ vscode_extensions }}"
  when: vscode_extensions is defined
