---
- name: install chrome
  become: true

  block:
    - name: add vscode repo key
      ansible.builtin.apt_key:
        url: "{{ vscode.repo_key }}"
        state: present

    - name: add vscode repository
      ansible.builtin.apt_repository:
        repo: "{{ vscode.repo }}"
        filename: vscode
        state: present

    - name: install vscode
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - code
