---
- name: install vscode snap
  become: yes
  snap:
    name: code
    state: present
    classic: yes

- name: list vscode extensions
  command: "code --list-extensions"
  register: vscode_installed_extensions

- name: install vscode extensions
  command: "code --install-extension '{{ item }}'"
  loop: "{{ vscode_extensions }}"
  when: (vscode_extensions is defined) and (item not in vscode_installed_extensions.stdout|lower)