---
- name: install vscode snap
  become: yes
  snap:
    name: code
    state: present
    classic: yes

- name: list vscode extensions
  command: "{{ vscode_bin }} --list-extensions"
  register: vscode_installed_extensions
  changed_when: false

- name: install vscode extensions
  command: "{{ vscode_bin }} --install-extension '{{ item }}'"
  loop: "{{ vscode_extensions }}"
  when: (vscode_extensions is defined) and (item not in vscode_installed_extensions.stdout|lower)
