---
- name: install Flatpak
  become: yes

  package:
    name: flatpak
    state: present

- name: add Flathub repo
  flatpak_remote:
    name: Flathub
    state: present
    flatpakrepo_url: "{{ flathub_repo }}"


- name: install Spotify flatpak
  flatpak:
    name: "{{ flatpak_spotify_ref }}"
    state: present

- name: install Signal flatpak
  flatpak:
    name: "{{ flatpak_signal_ref }}"
    state: present