---
configure_dconf:    yes
configure_grub:     yes
configure_journald: yes
install_awscli:     yes
install_chrome:     yes

# consider using snap version
# disable for now; not all packages available on disco
install_docker:     no

install_dotfiles:   yes
install_gcloud:     yes
install_kubernetes: yes
install_node:       yes
install_python:     yes
install_scripts:    yes
install_signal:     yes
install_spotify:    no
install_terraform:  yes
install_tlp:        yes
install_vscode:     yes

vscode_extensions:
  - shan.code-settings-sync

packages:
  - build-essential
  - chrome-gnome-shell
  - curl
  - git
  - gnome-tweak-tool
  - neovim
  - shellcheck
  - ssh-askpass-gnome
  - strace
  - unzip

git:
  name:       Łukasz Jendrysik
  email:      scadu9@gmail.com
  #signingkey: 81428558222B6C926149C6814F521D0B0F66261E
  #gpgsign:    false

grub_options: "quiet splash btusb.enable_autosuspend=n"
