---
install_dotfiles: yes
install_vscode: yes
install_chrome: yes
install_gcloud: yes
install_kubernetes: yes
install_terraform: yes
install_python: yes

vscode_extensions:
  - shan.code-settings-sync

packages:
  - build-essential
  - curl
  - git
  - neovim
  - shellcheck
  - strace
  - unzip
  - gnome-tweak-tool
  - chrome-gnome-shell

git:
  name: Łukasz Jendrysik
  email: scadu@disroot.org
  signingkey: 81428558222B6C926149C6814F521D0B0F66261E
  gpgsign: false
