---
install_chrome:     yes
install_dotfiles:   yes
install_gcloud:     yes
install_kubernetes: yes
install_python:     yes
install_terraform:  yes
install_vscode:     yes
install_signal:     yes
remove_dock:        yes

vscode_extensions:
  - shan.code-settings-sync

packages:
  - build-essential
  - chrome-gnome-shell
  - curl
  - git
  - gnome-tweak-tool
  - neovim
  - shellcheck
  - strace
  - tilix
  - unzip

git:
  name:       Łukasz Jendrysik
  email:      scadu@disroot.org
  signingkey: 81428558222B6C926149C6814F521D0B0F66261E
  gpgsign:    false
