---
# desktop things
configure_dconf:    yes

# dots and scripts
install_dotfiles:   yes
install_scripts:    yes

# apps
install_signal:     yes
install_spotify:    yes
install_slack:      yes
install_chrome:     yes

# system configuration
configure_grub:     yes
configure_journald: yes
install_tlp:        yes

# tools
## docker and k8s
install_docker:     yes
install_kubectl:    yes
install_helm:       yes

## IaC
install_terraform:  yes

## aws
install_awscli:     yes

## gcp
install_gcloud:     yes

## editor
install_vscode:     yes

# languages
install_node:       yes
install_python:     yes

vscode_extensions:
  - shan.code-settings-sync

packages:
  - build-essential
  - chrome-gnome-shell
  - curl
  - git
  - gnome-tweak-tool
  - htop
  - lm-sensors
  - neovim
  - shellcheck
  - ssh-askpass-gnome
  - strace
  - unzip

git:
  name:       Łukasz Jendrysik
  email:      scadu9@gmail.com
  #signingkey: 81428558222B6C926149C6814F521D0B0F66261E
  #gpgsign:    false

grub_options: "quiet splash btusb.enable_autosuspend=n"
