---
install_dotfiles: yes
install_vscode: yes

vscode_extensions:
  - shan.code-settings-sync

git:
  name: Łukasz Jendrysik
  email: scadu@disroot.org
  signingkey: 81428558222B6C926149C6814F521D0B0F66261E
  gpgsign: false
