---
# dots and scripts
install_dotfiles: yes

# languages
install_python: yes

# tools
## docker and k8s
install_kubectl: yes

## IaC
install_terraform: yes

packages:
  - build-essential
  - curl
  - git
  - neovim
  - shellcheck
  - strace
  - unzip
  - zsh

git:
  name: Łukasz Jendrysik
  email: scadu@disroot.org
  signingkey: 81428558222B6C926149C6814F521D0B0F66261E
  gpgsign: false
