---
install_python: yes
install_terraform: yes
install_dotfiles: yes
install_kubernetes: yes

packages:
  - build-essential
  - curl
  - git
  - neovim
  - shellcheck
  - strace
  - unzip
  - zsh

git:
  name: Łukasz Jendrysik
  email: scadu@disroot.org
  signingkey: 81428558222B6C926149C6814F521D0B0F66261E
  gpgsign: false
