---
- name: install docker
  become: true

  block:
    - name: add docker upstream repo key
      ansible.builtin.apt_key:
        url: "{{ docker.repo_key }}"
        keyring: "{{ docker.keyring }}"
        state: present

    - name: add docker upstream repository
      ansible.builtin.apt_repository:
        repo: "{{ docker.repo }}"
        filename: docker
        state: present

    - name: install docker from upstream repository
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin 
          - docker-compose-plugin

    - name: add my user to docker group
      become: true

      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        update_password: on_create
        groups: docker
        append: true
