vscode_repo_key: https://packages.microsoft.com/keys/microsoft.asc

rpm_repos:
  onepassword:
    name: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc

password_rpm_uri: https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm

go:
  version: 1.20.1
  checksum: "sha256:000a5b1fca4f75895f78befeb2eecf10bfff3c428597f3f1e69133b63b911b02"