---
# tfenv
tfenv_version: 3.0.0
tfenv_url: "https://github.com/tfutils/tfenv/archive/v{{ tfenv_version }}.tar.gz"
tfenv_checksum: sha256:8121f269a1c6214d7621a06e7f40e114e0a1c38a87d5b57585405aa4862ff0f0"


# list of AWS tools installed via pip
aws_tools: [
  "awscli",
  "aws-sam-cli"
]

# google chrome
chrome_repo_key: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
chrome_repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"

# tarsnap
tarsnap_repo_key: "https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc"
tarsnap_repo: "deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"

# docker upstream repo
docker_repo_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

# define local dir
user_local_dir: "{{ ansible_user_dir }}/.local"

# go
go_version: 1.20.1
go_checksum: "sha256:000a5b1fca4f75895f78befeb2eecf10bfff3c428597f3f1e69133b63b911b02"

packages:
  - build-essential
  - curl
  - fonts-firacode
  - fonts-powerline
  - git
  - htop
  - jq
  - neovim
  - shellcheck
  - unzip

gnome_packages:
  - chrome-gnome-shell
  - gnome-tweak-tool
  - ssh-askpass-gnome
  
# vscode snap
vscode_bin: "/snap/code/current/usr/share/code/bin/code"
