user_local_dir: "{{ ansible_user_dir }}/.local"

packages:
  - ripgrep
  - jq
  - neovim
  - fira-code-fonts

rpm:
  onepassword:
    name: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc

  vscode:
    name: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
