---
# terraform
terraform_version: 0.11.14
terraform_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
terraform_checksum: "sha256:9b9a4492738c69077b079e595f5b2a9ef1bc4e8fb5596610f69a6f322a8af8dd"

# chrome
chrome_repo_key: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
chrome_repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"

# vscode
ms_repo_key: "https://packages.microsoft.com/keys/microsoft.asc"
vscode_repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

# kubernetes
kubernetes_repo_key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
kubernetes_repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"

# gcloud-sdk
gcloud_repo_key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
gcloud_repo: "deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main"

# helm
helm_version: 2.14.0
helm_url: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
helm_checksum: "sha256:b5f6a1e642971af1363cadbe1f7f37c029c11dd93813151b521c0dbeacfbdaa9"

# tarsnap
tarsnap_repo_key: "https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc"
tarsnap_repo: "deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"

# docker
docker_repo_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

# prezto
prezto_repo: "https://github.com/scadu/prezto.git"

# define local dir
user_local_dir: "{{ ansible_user_dir }}/.local"

# node snap
snap_node_channel: "12/stable"