---
# terraform
terraform_version: 0.11.11
terraform_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
terraform_checksum: "sha256:94504f4a67bad612b5c8e3a4b7ce6ca2772b3c1559630dfd71e9c519e3d6149c"

# chrome
chrome_repo_key: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
chrome_repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"

# vscode
ms_repo_key: "https://packages.microsoft.com/keys/microsoft.asc"
vscode_repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

# kubernetes
kubernetes_repo_key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
kubernetes_repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"

# helm
helm_version: 2.12.3
helm_url: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
helm_checksum: "sha256:3425a1b37954dabdf2ba37d5d8a0bd24a225bb8454a06f12b115c55907809107"
# tarsnap
tarsnap_repo_key: "https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc"
tarsnap_repo: "deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"

# prezto
prezto_repo: "https://github.com/scadu/prezto.git"