---
# terraform
terraform_version: 0.11.14
terraform_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
terraform_checksum: "sha256:9b9a4492738c69077b079e595f5b2a9ef1bc4e8fb5596610f69a6f322a8af8dd"

# chrome
chrome_repo_key: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
chrome_repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"

# tarsnap
tarsnap_repo_key: "https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc"
tarsnap_repo: "deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"

# docker upstream repo
docker_repo_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

# prezto
prezto_repo: "https://github.com/scadu/prezto.git"

# define local dir
user_local_dir: "{{ ansible_user_dir }}/.local"

# node snap
snap_node_channel: "12/stable"

# kubectl snap
kubectl_snap_channel: "1.14"

# helm snap
helm_snap_channel: "latest/stable"