---
tfenv:
  version: 3.0.0

go:
  version: 1.20.1
  checksum: "sha256:000a5b1fca4f75895f78befeb2eecf10bfff3c428597f3f1e69133b63b911b02"

chrome:
  repo_key: https://dl-ssl.google.com/linux/linux_signing_key.pub
  repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"

docker:
  repo_key: https://download.docker.com/linux/ubuntu/gpg
  keyring: /etc/apt/keyrings/docker.gpg
  repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

vscode:
  repo_key: https://packages.microsoft.com/keys/microsoft.asc
  keyring: /etc/apt/keyrings/packages.microsoft.gpg
  repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"

# list of AWS tools installed via pip
aws_tools: ["awscli", "aws-sam-cli"]

# define local dir
user_local_dir: "{{ ansible_user_dir }}/.local"

packages:
  - build-essential
  - curl
  - fonts-firacode
  - fonts-powerline
  - git
  - jq
  - shellcheck
  - unzip

gnome_packages:
  - chrome-gnome-shell
  - gnome-tweak-tool
  - ssh-askpass-gnome
