---
terraform_version: 0.11.8
terraform_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
terraform_checksum: "sha256:84ccfb8e13b5fce63051294f787885b76a1fedef6bdbecf51c5e586c9e20c9b7"

flathub_repo: https://flathub.org/repo/flathub.flatpakrepo
flatpak_spotify_ref: https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
flatpak_signal_ref: https://flathub.org/repo/appstream/org.signal.Signal.flatpakref