---
# tfenv
tfenv_version: 1.0.1
tfenv_url: "https://github.com/tfutils/tfenv/archive/v{{ tfenv_version }}.tar.gz"
tfenv_checksum: sha256:8121f269a1c6214d7621a06e7f40e114e0a1c38a87d5b57585405aa4862ff0f0"

# terragrunt
terragrunt_version: 0.19.8
terragrunt_url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64"
terragrunt_checksum: "sha256:70e81e5cc7a7c504557103e2ba90ac4c3c90a01bceffb2a34d4419643cf09998"

# chrome
chrome_repo_key: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
chrome_repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"

# tarsnap
tarsnap_repo_key: "https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc"
tarsnap_repo: "deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"

# docker upstream repo
docker_repo_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

# prezto
prezto_repo: "https://github.com/scadu/prezto.git"

# define local dir
user_local_dir: "{{ ansible_user_dir }}/.local"

# node snap
snap_node_channel: "12/stable"

# kubectl snap
kubectl_snap_channel: "1.14"

# helm snap
helm_snap_channel: "latest/stable"