---
- name: restart journald
  become: yes
  systemd:
    name: systemd-journald
    state: restarted

- name: start syncthing
  become: yes
  systemd:
    name: "syncthing@{{ ansible_user_id }}.service"
    state: started
    enabled: yes

- name: start tlp
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - tlp
    - tlp-sleep

- name: mask systemd-rfkill
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: no
    masked: yes
  with_items:
    - systemd-rfkill.socket
    - systemd-rfkill.service

- name: start unattended-upgrades
  become: yes
  systemd:
    name: unattended-upgrades
    enabled: yes
    state: restarted

- name: regenerate grub cfg
  become: yes
  command: "grub-mkconfig -o /boot/grub/grub.cfg"

- name: refresh font cache
  command: fc-cache -f -v
