---
- name: restart journald
  become: true
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: start unattended-upgrades
  become: true
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: restarted

- name: refresh font cache
  ansible.builtin.command: fc-cache -f -v
