---
- name: restart journald
  become: true
  systemd:
    name: systemd-journald
    state: restarted

- name: start unattended-upgrades
  become: true
  systemd:
    name: unattended-upgrades
    enabled: yes
    state: restarted

- name: refresh font cache
  command: fc-cache -f -v
