---
packages:
  - git
  - vim
  - ansible
  #- thunderbird
  - zsh
  - ShellCheck
  - tmux
  - htop
  - iftop
  - ncdu
  - aria2
  - youtube-dl
  - mpv
  - keepassxc
  - redshift-gtk
  - chrome-gnome-shell
  - gnome-tweak-tool
  - asciinema